siteTitle = "Blog by Lukas Grasse"
siteDescr = "A blog about Software, Robotics, Coffee, and many other interesting things."
siteAuthor = "Lukas Grasse"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"
